import Navbar from "@/components/Navbar";
import { Montserrat } from "next/font/google";
import "./global.css";
import SearchBar from "@/components/SearchBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const monserratFont = Montserrat({
  weight: ["300", "400", "500", "600", "700"],
  styles: ["normal", "italic"],
  subsets: ["latin-ext"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={monserratFont.className} suppressHydrationWarning={true}>
        <Navbar />
        <main className="grid place-items-center p-4 h-auto">{children}</main>
      </body>
    </html>
  );
}
